src/accounts/api/urls.py
from django.conf.urls import url
from posts.api.views import PostListAPIView, PostCreateAPIView, ShareAPIView


urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/post/$', PostListAPIView.as_view(), name='List'),
]

src/accounts/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import UserDetailView, UserFollowView

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url='/')),
    # url(r'^create/$', PostCreateView.as_view(), name='create'),
    
    url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<username>[\w.@+-]+)/follow/$', UserFollowView.as_view(), name='follow'),

    # url(r'^update/(?P<pk>\d+)/$', PostUpdateView.as_view(), name='update'),
    # url(r'^delete/(?P<pk>\d+)/$', PostDeleteView.as_view(), name='delete'),
    # url(r'^list/', PostListView.as_view(), name='list'),
]

src/posts/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import PostDetailView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, ShareView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/')),
    url(r'^create/$', PostCreateView.as_view(), name='create'),
    url(r'^detail/(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^share/(?P<pk>\d+)/$', ShareView.as_view(), name='share'),
    url(r'^update/(?P<pk>\d+)/$', PostUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', PostDeleteView.as_view(), name='delete'),
    url(r'^list/', PostListView.as_view(), name='list'),
]

src/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.db.models.signals import post_save

# Create your models here.

class UserProfileManager(models.Manager):
    use_for_related_fields = True

    def all(self):
        qs = self.get_queryset().all()

        try:
            if self.instance:
                qs = qs.exclude(user=self.instance)
        except:
            pass
        return qs
    
    def toggle_follow(self, user, to_toggle_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if to_toggle_user in user_profile.following.all():
            user_profile.following.remove(to_toggle_user)
            added = False
        else:
            user_profile.following.add(to_toggle_user)
            added = True
        return added
    
    def is_following(self, user, followed_by_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if created:
            return False
        if followed_by_user in user_profile.following.all():
            return True
        return False

    def recommended(self, user, limit_to=10):
        profile = user.profile
        following = profile.get_following()
        qs = self.get_queryset().exclude(user__in=following).exclude(id=profile.id).order_by("?")[:limit_to]
        return qs
 
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
    following = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, related_name='followed_by')

    objects= UserProfileManager()

    def get_following(self):
        users = self.following.all()
        return users.exclude(username = self.user.username)

    def get_follow_url(self):
        return reverse_lazy("profiles:follow", kwargs={'username':self.user.username})
    
    def get_absolute_url(self):
        return reverse_lazy("profiles:detail", kwargs={"username":self.user.username})
    
    def __str__(self):
        return str(self.following.all().count())


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    print(instance)
    if created:
        new_profile = UserProfile.objects.get_or_create(user=instance)


post_save.connect(post_save_user_receiver, sender=settings.AUTH_USER_MODEL)
    

src/posts/models.py
import re

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from hashtags.signals import parsed_hashtags
# Create your models here.

class PostManager(models.Manager):
    def share(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj

        qs = self.get_queryset().filter(user=user, parent= og_parent).filter(timestamp__year=timezone.now().year,timestamp__month=timezone.now().month, timestamp__day=timezone.now().day, comment = False)
        if qs.exists():
            return None

        obj = self.model(
            parent = og_parent,
            user = user,
            content = parent_obj.content
        )
        obj.save()
        return obj

    def like_toggle(self, user, post_obj):
        if user in post_obj.liked.all():
            is_liked = False
            post_obj.liked.remove(user)
        else:
            is_liked = True
            post_obj.liked.add(user)
        return is_liked

class Post(models.Model):
    parent = models.ForeignKey("self",blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=50, blank=True, null=True)
    content = models.CharField(max_length=155)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL,null=True, default=0, related_name="liked")
    comment = models.BooleanField(verbose_name="Is a comment?", default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = PostManager()
    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse("post:detail", kwargs={"pk": self.pk})
    
    def get_parent(self):
        the_parent = self
        if self.parent:
            the_parent = self.parent
        return the_parent

    def get_children(self):
        parent = self.get_parent()
        qs = Post.objects.filter(parent=self)
        qs_parent = Post.objects.filter(pk=parent.id)
        return (qs | qs_parent)


    def __str__(self):
        return self.content


def post_save_receiver(sender, instance, created, *args, **kwargs):
    if created and not instance.parent:
        user_regx = r'@(?P<username>[\w.@+-]+)'
        usernames = re.findall(user_regx, instance.content)

        hash_regx = r'#(?P<hashtag>[\w\d-]+)'
        hashtags = re.findall(hash_regx, instance.content)
        parsed_hashtags.send(sender=instance.__class__, hashtag_list = hashtags)


post_save.connect(post_save_receiver, sender=Post)

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Password must match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__icontains=username).exists():
            raise forms.ValidationError("This username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__icontains=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email

src/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView
from django.views import View
from django.contrib.auth.models import User
from .models import UserProfile
from django.views.generic.edit import FormView
from .forms import UserRegisterForm
# Create your views here.

class UserDetailView(DetailView):
    qeryset = User.objects.all()
    template_name = 'accounts/user_detail.html'

    def get_object(self):
            return get_object_or_404(User, username__iexact=self.kwargs.get("username"))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        following = UserProfile.objects.is_following(self.request.user,self.get_object())
        context["sidebar"] = False
        context["following"] = following
        context["recommended"] = UserProfile.objects.recommended(self.request.user,10)
        return context

class UserRegisterView(FormView):
    template_name = 'registration/user_register_form.html'
    form_class = UserRegisterForm
    success_url = '/login'

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        new_user = User.objects.create(username=username, email=email)
        new_user.set_password(password)
        new_user.save()
        return super(UserRegisterView, self).form_valid(form)

class UserFollowView(View):

    def get(self, request, username, *args, **kwargs):
        toggle_user = get_object_or_404(User, username__iexact=username)
        if request.user.is_authenticated():
            is_following = UserProfile.objects.toggle_follow(request.user, toggle_user)
        return redirect("profiles:detail", username=username)
    

src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% load static %}

{% block scripts %}
<script src="{% static 'scripts/post_list.js' %}"></script>
{% endblock scripts %}

{% block sidebar %}
<!-- {% url 'profiles:user_detail' as profilelink %}
{% include "sidebar.html" with profile="active" profile_link=profilelink %} -->
{% endblock sidebar %}

{% block main-container-bar %}
<main class="main-content  col-sm-12 p-0 {% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
    <div class="main-navbar sticky-top bg-white">
{% endblock main-container-bar %}



{% block navbar-logo %}
<a class="navbar-brand w-25 mr-0" href="#" style="line-height: 25px;">
    <div class="d-table m-auto">
        <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
    </div>
</a>
{% endblock navbar-logo %}


{% block page-header %}

{% endblock page-header %}

{% block content %}
<div class="row mt-4">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-3">
      <div class="card card-small mb-4 pt-3">
        <div class="card-header border-bottom text-center">
          <div class="mb-3 mx-auto">
            <img class="rounded-circle" src="{% static 'images/avatars/0.jpg'%}" alt="User Avatar" width="180"> </div>
          <h4 class="mb-0"> {{ object.first_name }} {{ object.last_name }} </h4>
          <span class="text-muted d-block mb-2">@{{object.username}}</span>
          <a href="{{ object.profile.get_follow_url}}" class="mb-2 btn btn-sm btn-pill btn-outline-primary mr-2">
            <i class="material-icons mr-1">person_add</i> {% if following %} Unfollow {% else %} Follow {% endif %} </a>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item px-4">
            <div class="progress-wrapper">
              <strong class="text-muted d-block mb-2">Workload</strong>
              <div class="progress progress-sm">
                <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100" style="width: 74%;">
                  <span class="progress-value">74%</span>
                </div>
              </div>
            </div>
          </li>
          <li class="list-group-item p-4">
            <strong class="text-muted d-block mb-2">Description</strong>
            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio eaque, quidem, commodi soluta qui quae minima obcaecati quod dolorum sint alias, possimus illum assumenda eligendi cumque?</span>
          </li>
          <li class="list-group-item p-4">
              <strong class="text-muted d-block mb-2">Recommended Users</strong>
              {% for profile in recommended %}
              <a href="/{{ profile.user.username }}">{{ profile.user.username }}</a><br>
              {% empty %}
              <p>Currently no User is recommended for you.</p>
              {% endfor %}
            </li>
        </ul>
      </div>
    </div>
    <div class="col-lg-7">
      <div class="card card-small mb-4 p-2">

        <ul class="list-group list-group-flush">
          <li class="list-group-item p-3">
            <div class="row">
              <div class="col-lg-4 ">
                <h5>Posts: <a href="#" data-toggle="modal" data-target="#exampleModalCenter"> {{object.post_set.count}} </a></h5>
              </div>
              <div class="col-lg-4">
                  <h5>Followers: <a href="#" data-toggle="modal" data-target="#followersModal"> {{ object.followed_by.all.count}} </a></h5>
              </div>
              <div class="col-lg-4 ">
                  <h5>Following: <a href="#" data-toggle="modal" data-target="#followingModal"> {{ object.profile.get_following.count }} </a></h5>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div  id="post-container" data-url="/api/{{ object.username }}/post/">

      </div>
      <a href="#" id="loadmore">Load More posts</a>

    </div>
    <div class="col-lg-1">
    </div>
  </div>

  <!-- followersModal -->
<div class="modal fade" id="followersModal" tabindex="-1" role="dialog" aria-labelledby="followersModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followersModalTitle">Followers <small>{{ object.followed_by.all.count}}</small> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for profile in object.followed_by.all %}
          <a href="/{{ profile.user.username }}">{{ profile.user.username }}</a><br>
        {% empty %}
        <h4>Currently no User is following you.</h4>
        {% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

  <!-- followingModal -->
  <div class="modal fade" id="followingModal" tabindex="-1" role="dialog" aria-labelledby="followingModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="followingModalTitle">Following <small>{{ object.profile.get_following.count }}</small> </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for user in object.profile.get_following %}
            <a href="/{{ user.username }}"> {{ user.username }} </a> <br>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}