src/CodeColeo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from posts.views import PostListView
from hashtags.views import HashTagView
from hashtags.api.views import TagAPIView

from .views import SearchView
from posts.api.views import SearchAPIView
from accounts.views import UserRegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', PostListView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name="hashtag"),
    url(r'^post/', include('posts.urls', namespace="post")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^', include('accounts.urls', namespace="profiles")),
    url(r'^api/post/', include('posts.api.urls', namespace="post-api")),
    url(r'^api/', include('accounts.api.urls', namespace="profiles-api")),
    url(r'^api/search/$', SearchAPIView.as_view(), name="search-api"),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagAPIView.as_view(), name="tags-api"),

]

if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/posts/api/urls.py
from django.conf.urls import url
from .views import PostListAPIView, PostCreateAPIView, ShareAPIView, LikeToggleAPIView, PostDetailAPIView


urlpatterns = [
    # url(r'^$', RedirectView.as_view(url='/')),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    # url(r'^search/$', SearchAPIView.as_view(), name='api-search'),
    url(r'^share/(?P<pk>\d+)/$', ShareAPIView.as_view(), name='share'),
    url(r'^like/(?P<pk>\d+)/$', LikeToggleAPIView.as_view(), name='like-toggle'),
    url(r'^detail/(?P<pk>\d+)/$', PostDetailAPIView.as_view(), name='Detail'),
    # url(r'^update/(?P<pk>\d+)/$', PostUpdateView.as_view(), name='Update'),
    # url(r'^delete/(?P<pk>\d+)/$', PostDeleteView.as_view(), name='Delete'),
    url(r'^$', PostListAPIView.as_view(), name='List'),
]

src/posts/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import PostDetailView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, ShareView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/')),
    url(r'^create/$', PostCreateView.as_view(), name='create'),
    url(r'^detail/(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^share/(?P<pk>\d+)/$', ShareView.as_view(), name='share'),
    url(r'^update/(?P<pk>\d+)/$', PostUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', PostDeleteView.as_view(), name='delete'),
    url(r'^list/', PostListView.as_view(), name='list'),
]

src/posts/models.py
import re

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from hashtags.signals import parsed_hashtags
# Create your models here.

class PostManager(models.Manager):
    def share(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj

        qs = self.get_queryset().filter(user=user, parent= og_parent).filter(timestamp__year=timezone.now().year,timestamp__month=timezone.now().month, timestamp__day=timezone.now().day, comment = False)
        if qs.exists():
            return None

        obj = self.model(
            parent = og_parent,
            user = user,
            content = parent_obj.content
        )
        obj.save()
        return obj

    def like_toggle(self, user, post_obj):
        if user in post_obj.liked.all():
            is_liked = False
            post_obj.liked.remove(user)
        else:
            is_liked = True
            post_obj.liked.add(user)
        return is_liked

class Post(models.Model):
    parent = models.ForeignKey("self",blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=50, blank=True, null=True)
    content = models.CharField(max_length=155)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL,null=True, default=0, related_name="liked")
    comment = models.BooleanField(verbose_name="Is a comment?", default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = PostManager()
    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse("post:detail", kwargs={"pk": self.pk})
    
    def get_parent(self):
        the_parent = self
        if self.parent:
            the_parent = self.parent
        return the_parent

    def get_children(self):
        parent = self.get_parent()
        qs = Post.objects.filter(parent=self)
        qs_parent = Post.objects.filter(pk=parent.id)
        return (qs | qs_parent)


    def __str__(self):
        return self.content


def post_save_receiver(sender, instance, created, *args, **kwargs):
    if created and not instance.parent:
        user_regx = r'@(?P<username>[\w.@+-]+)'
        usernames = re.findall(user_regx, instance.content)

        hash_regx = r'#(?P<hashtag>[\w\d-]+)'
        hashtags = re.findall(hash_regx, instance.content)
        parsed_hashtags.send(sender=instance.__class__, hashtag_list = hashtags)


post_save.connect(post_save_receiver, sender=Post)

src/posts/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):
    content = forms.CharField(label='',
                    widget=forms.Textarea(attrs={'placeholder':'Whats are you thinking?', 'class':'form-control form-control-lg mb-3'}
                    ))
    class Meta:
        model = Post
        fields = [
            'content',
        ]

    def clean_content(self,*args, **kwargs):
        content = self.cleaned_data.get("content")
        if content == "":
            raise forms.ValidationError("Field cannot be empty")
        return content

src/posts/api/views.py
from rest_framework import generics
from rest_framework import permissions
from .serializers import PostModelSerializer
from django.db.models import Q
from posts.models import Post
from .pagination import StandardResultsPagination
from rest_framework.views import APIView
from rest_framework.response import Response


class LikeToggleAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    def get(self, request, pk, format=None):
        post_qs = Post.objects.filter(pk=pk)
        message = "Not Allowed"
        if request.user.is_authenticated():
            is_liked = Post.objects.like_toggle(request.user, post_qs.first())
            return Response({"liked": is_liked})
        return Response({"message": message}, status=400)

class ShareAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    def get(self, request, pk, format=None):
        post_qs = Post.objects.filter(pk=pk)
        message = "Not allowed"
        if post_qs.exists() and post_qs.count() == 1:
            # if request.user.is_authenticated():
            new_post = Post.objects.share(request.user, post_qs.first())
            if new_post is not None:
                data = PostModelSerializer(new_post).data
            message = "Cannot retweet the same in 1 day"
        return Response({"message": message}, status=400)

class PostCreateAPIView(generics.CreateAPIView):
    serializer_class = PostModelSerializer
    permission_classes = [permissions.IsAuthenticated]
    
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostDetailAPIView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostModelSerializer
    pagination_class = StandardResultsPagination
    permission_classes = [permissions.AllowAny]

    def get_queryset(self, *args, **kwargs):
        post_id = self.kwargs.get("pk")
        qs = Post.objects.filter(pk=post_id)
        if qs.exists() and qs.count() == 1:
            parent_obj = qs.first()
            qs1 = parent_obj.get_children()
            qs = (qs | qs1).distinct().extra(select={"parent_id_null": 'parent_id IS NULL'})
        return qs.order_by("-parent_id_null","-timestamp")

class PostListAPIView(generics.ListAPIView):
    serializer_class = PostModelSerializer
    pagination_class = StandardResultsPagination

    def get_serializer_context(self, *args, **kwargs):
            context = super(PostListAPIView, self).get_serializer_context(*args, **kwargs)
            context['request'] = self.request
            return context

    def get_queryset(self, *args, **kwargs):
        requested_user = self.kwargs.get("username")
        if requested_user:
            qs = Post.objects.filter(user__username=requested_user).order_by('-timestamp')
        else:
            im_following = self.request.user.profile.get_following()
            qs1 = Post.objects.filter(user__in=im_following)
            qs2 = Post.objects.filter(user=self.request.user)
            qs = (qs1 | qs2).distinct().order_by('-timestamp')
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains = query) |
                Q(user__username__icontains = query))
        return qs
    

class SearchAPIView(generics.ListAPIView):
    queryset = Post.objects.all().order_by("-timestamp")
    serializer_class = PostModelSerializer
    pagination_class = StandardResultsPagination

    def get_serializer_context(self, *args, **kwargs):
        context = super(SearchAPIView, self).get_serializer_context(*args, **kwargs)
        context['request'] = self.request
        return context

    def get_queryset(self, *args, **kwargs):
        qs = self.queryset
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains = query) |
                Q(user__username__icontains = query))
        return qs


    

src/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.views import View
from .models import Post
from .forms import PostModelForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ShareView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        if request.user.is_authenticated():
            new_post = Post.objects.share(request.user, post)
            return HttpResponseRedirect("/")
        return HttpResponseRedirect(post.get_absolute_url())

class PostCreateView(CreateView):
    form_class = PostModelForm
    template_name = 'posts/post_create.html'
    # success_url = "/post/list/"

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super(PostCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sidebar"] = True
        return context
    
class PostUpdateView(UpdateView):
    queryset = Post.objects.all()
    form_class = PostModelForm
    template_name = 'posts/post_update.html'
    success_url = "/post/list/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sidebar"] = False
        return context

class PostDeleteView(DeleteView):
    model = Post
    template_name = "posts/post_delete.html"
    success_url = reverse_lazy('post:List')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sidebar"] = False
        return context
    

class PostDetailView(DetailView):
    template_name = "posts/post_detail.html"
    # queryset = Post.objects.all()

    def get_object(self):
        pk = self.kwargs.get('pk')
        return Post.objects.get(id=pk)

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["sidebar"] = False
        return context
    

class PostListView(LoginRequiredMixin, ListView):
    template_name = "posts/post_list.html"

    def get_queryset(self, *args, **kwargs):
        qs = Post.objects.all().order_by('-timestamp')
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains = query) |
                Q(user__username__icontains = query))
        return qs

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context["sidebar"] = False
        context['form'] = PostModelForm()
        context['post_url'] = reverse_lazy("post:create")
        return context

src/posts/templates/posts/check.html
{% extends "base.html" %}
{% load static %}
{% block sidebar %}
 {% include "sidebar.html" with home = 'active' home_link='{% url "post:List" %}' %}
{% endblock sidebar %}

{% block main-container-bar %}
<main class="main-content  col-sm-12 p-0 {% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
    <div class="main-navbar sticky-top bg-white">
{% endblock main-container-bar %}


{% block navbar-logo %}
    <a class="navbar-brand w-25 mr-0" href="#" style="line-height: 25px;">
        <div class="d-table m-auto">
            <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
        </div>
    </a>
{% endblock navbar-logo %}


{% block page-header %}

{% endblock page-header %}

{% block content %}

{% endblock content %}

src/posts/templates/posts/form.html
<form action="{% if action_url %} {{ action_url }} {% endif %}" class="post-form" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{{btn_title}}" class="mb-1 btn btn-sm btn-outline-primary mt-0 ml-auto"/>
</form>

src/posts/templates/posts/post_create.html
{% extends "base.html" %}
{% load static %}
{% block sidebar %}
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
        <div class="main-navbar">
          <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
              <div class="d-table m-auto">
                <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
              </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
              <i class="material-icons">&#xE5C4;</i>
            </a>
          </nav>
        </div>
        <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
          <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <i class="fas fa-search"></i>
              </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
        </form>
        <div class="nav-wrapper">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link " href="index.html">
                <i class="material-icons">edit</i>
                <span>Blog Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="components-blog-posts.html">
                <i class="material-icons">vertical_split</i>
                <span>Blog Posts</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="add-new-post.html">
                <i class="material-icons">note_add</i>
                <span>Add New Post</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="form-components.html">
                <i class="material-icons">view_module</i>
                <span>Forms &amp; Components</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="tables.html">
                <i class="material-icons">table_chart</i>
                <span>Tables</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="user-profile-lite.html">
                <i class="material-icons">person</i>
                <span>User Profile</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="errors.html">
                <i class="material-icons">error</i>
                <span>Errors</span>
              </a>
            </li>
          </ul>
        </div>
      </aside>
{% endblock sidebar %}

{% block main-container-bar %}
<main class="main-content  col-sm-12 p-0 {% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
    <div class="main-navbar sticky-top bg-white">
{% endblock main-container-bar %}


{% block navbar-logo %}

{% endblock navbar-logo %}


{% block page-header %}
<div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle">Post</span>
            <h3 class="page-title">Add New Post</h3>
        </div>
    </div>
{% endblock page-header %}

{% block content %}
<div class="row">
        <div class="col-lg-9 col-md-12">
          <!-- Add New Post Form -->
          <div class="card card-small mb-3">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="POST" class="mb-2 btn btn-sm btn-outline-primary mr-1"/>
                </form>
                {% include "posts/form.html" with form=form action_url=post_url btn_title='POST' form_id='post-form' %}

            </div>
          </div>
          <!-- / Add New Post Form -->
        </div>
        <div class="col-lg-3 col-md-12">
          <!-- Post Overview -->
          <div class='card card-small mb-3'>
            <div class="card-header border-bottom">
              <h6 class="m-0">Categories</h6>
            </div>
            <div class='card-body p-0'>
              <ul class="list-group list-group-flush">
                <li class="list-group-item px-3 pb-2">
                  <div class="custom-control custom-checkbox mb-1">
                    <input type="checkbox" class="custom-control-input" id="category1">
                    <label class="custom-control-label" for="category1">Uncategorized</label>
                  </div>
                  <div class="custom-control custom-checkbox mb-1">
                    <input type="checkbox" class="custom-control-input" id="category2" checked>
                    <label class="custom-control-label" for="category2">Java</label>
                  </div>
                  <div class="custom-control custom-checkbox mb-1">
                    <input type="checkbox" class="custom-control-input" id="category3">
                    <label class="custom-control-label" for="category3">C++</label>
                  </div>
                  <div class="custom-control custom-checkbox mb-1">
                    <input type="checkbox" class="custom-control-input" id="category4">
                    <label class="custom-control-label" for="category4">Python</label>
                  </div>
                  <div class="custom-control custom-checkbox mb-1">
                    <input type="checkbox" class="custom-control-input" id="category5">
                    <label class="custom-control-label" for="category5">Php</label>
                  </div>
                </li>
                <li class="list-group-item d-flex px-3">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="New category" aria-label="Add new category" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-white px-2" type="button">
                        <i class="material-icons">add</i>
                      </button>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <!-- / Post Overview -->
        </div>
      </div>
{% endblock content %}

src/posts/templates/posts/post_delete.html
{% extends "base.html" %}
{% load static %}
{% block sidebar %}

{% endblock sidebar %}

{% block main-container-bar %}
<main class="main-content  col-sm-12 p-0 {% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
    <div class="main-navbar sticky-top bg-white">
{% endblock main-container-bar %}


{% block navbar-logo %}
<a class="navbar-brand w-25 mr-0" href="#" style="line-height: 25px;">
    <div class="d-table m-auto">
        <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
    </div>
</a>
{% endblock navbar-logo %}


{% block page-header %}
<div class="page-header row no-gutters py-4">
        <div class="col-lg-8 offset-lg-2 col-md-12 col-sm-4 text-center text-sm-left mb-0 pb-3 border-bottom">
            <span class="text-uppercase page-subtitle">Post</span>
            <h3 class="page-title">Delete</h3>
        </div>
    </div>
{% endblock page-header %}

{% block content %}
<div class="row">
        <div class="col-lg-8 col-md-12 offset-lg-2">
          <!-- Add New Post Form -->
          <div class="card card-small mb-3">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Are you sure you want to delete this post?</p>
                    <input type="submit" value="DELETE" class="mb-2 btn btn-sm btn-outline-primary mr-1"/>
                </form>
            </div>
          </div>
          <!-- / Add New Post Form -->
        </div>

      </div>
{% endblock content %}

src/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block sidebar %}

{% endblock sidebar %}

{% block scripts %}
<script>
	$(document).ready(function () {
			loadPostContainer("post-container", {{ object.id }})
	})
</script>
{% endblock scripts %}

{% block main-container-bar %}
<main class="main-content  col-sm-12 p-0 {% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
    <div class="main-navbar sticky-top bg-white"> 
{% endblock main-container-bar %}


{% block navbar-logo %}
<a class="navbar-brand w-25 mr-0" href="#" style="line-height: 25px;">
    <div class="d-table m-auto">
        <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
    </div>
</a>
{% endblock navbar-logo %}


{% block page-header %}

{% endblock page-header %}

{% block content %}
<div class="row mt-4">
  <div class="col-lg-8 offset-lg-2">
    <div id="post-container">

    </div>
  </div>
</div>
{% endblock content %}

src/posts/templates/posts/post_list.html
{% extends "base.html" %}
{% load static %}

{% block page-title %}

{% endblock page-title %}

{% block scripts %}
<script>
	$(document).ready(function () {
			loadPostContainer("post-container")
	});
</script>
{% endblock scripts %}

{% block sidebar %}
<!-- {% url 'post:list' as homelink %}
{% include "sidebar.html" with home="active" home_link=homelink %} -->
{% endblock sidebar %}

{% block main-container-bar %}
<main class="main-content{% if sidebar %} col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3 {% else %} col-lg-12 col-md-12 col-sm-12 p-0 {% endif %}">
		<div class="main-navbar sticky-top bg-white">
{% endblock main-container-bar %}


{% block navbar-logo %}
<a class="navbar-brand w-25 mr-0" href="#" style="line-height: 25px;">
        <div class="d-table m-auto">
            <span class="d-none d-md-inline ml-1" style="font-family: 'Press Start 2P', cursive; font-size: 24px; ">Code</span> <span class="d-none d-md-inline ml-1" style="font-family: 'Orbitron', sans-serif; font-size: 24px;">Coleo</span>
        </div>
    </a>
{% endblock navbar-logo %}


{% block page-header %}

{% endblock page-header %}

{% block content %}
		<div class="row mt-4">   
				<div class="col-lg-3">
						<div class="card card-small mb-4 pt-3">
						  <div class="card-header border-bottom text-center">
							<div class="mb-3 mx-auto">
							  <img class="rounded-circle" src="{% static 'images/avatars/0.jpg'%}" alt="User Avatar" width="110"> </div>
							<h4 class="mb-0">{{object.username}}</h4>
							<span class="text-muted d-block mb-2">Project Manager</span>
							<button type="button" class="mb-2 btn btn-sm btn-pill btn-outline-primary mr-2">
							  <i class="material-icons mr-1">person_add</i>Follow</button>
						  </div>
						  <ul class="list-group list-group-flush">
							<li class="list-group-item px-4">
							  <div class="progress-wrapper">
								<strong class="text-muted d-block mb-2">Workload</strong>
								<div class="progress progress-sm">
								  <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100" style="width: 74%;">
									<span class="progress-value">74%</span>
								  </div>
								</div>
							  </div>
							</li>
							<li class="list-group-item p-4">
							  <strong class="text-muted d-block mb-2">Description</strong>
							  <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio eaque, quidem, commodi soluta qui quae minima obcaecati quod dolorum sint alias, possimus illum assumenda eligendi cumque?</span>
							</li>
						  </ul>
						</div>
				</div>     
				<div class="col-lg-7">
					{% if not request.GET.q %}
						<div class="card card-small mb-3">
							<div class="card-body">
								{% include "posts/form.html" with form=form action_url=post_url btn_title='POST' form_id='post-form' %}
							</div>
						</div>
					{% endif %}
					<div  id="post-container" data-url="/api/post/">

					</div>
					<a href="#" id="loadmore">Load More posts</a>
				</div>
				<div class="col-lg-2">
						<div class="page-header row no-gutters py-0">
								<div class="col-12 col-sm-4 text-center text-sm-left mb-0">
										<span class="text-uppercase page-subtitle">Trending</span>
										<!-- <h3 class="page-title">Trending</h3> -->
								</div>
						</div>
						{% for Post in trending_posts %}
								<div class="card card-small card-post mb-4">
										<div class="card-body">
											<h5 class="card-title">Instantly gentleman contained belonging exquisite now direction</h5>
											<p class="card-text text-muted">West room at sent if year. Numerous indulged distance old law you. Total state as merit court green decay he. Steepest merit checking railway...</p>
										</div>
										<div class="card-footer border-top d-flex">
											<div class="card-post__author d-flex">
												{% static 'images/avatars/3.jpg' as profile_pic %}
												 {{profile_pic}} 
												<a href="#" class="card-post__author-avatar card-post__author-avatar--small" >Written by Anna Kunis</a>
												<div class="d-flex flex-column justify-content-center ml-3">
													<span class="card-post__author-name">Mark Jameson</span>
													<small class="text-muted">21 March 2011</small>
												</div>
											</div>
											<div class="my-auto ml-auto">
												<a class="btn btn-sm btn-white" href="#">
													<i class="far fa-bookmark mr-1"></i> Bookmark </a>
											</div>
										</div>
								</div>            
						{% endfor %}
				</div>
			</div>
{% endblock content %}